export default {
  // Skipped so applications can use 0 as fallback
  SKIP: 1 << 0,

  CREATE_MESSAGE: 1 << 1,
  VIEW_CHANNELS: 1 << 2,
  READ_MESSAGE_HISTORY: 1 << 3,
  CREATE_INVITE: 1 << 4,
  ADD_REACTIONS: 1 << 5,
  EMBED_LINKS: 1 << 6,
  ATTACH_FILES: 1 << 7,
  MASS_MENTIONS: 1 << 8,
  CHANGE_NICKNAME: 1 << 9,

  ADMINISTRATOR: 1 << 10,
  MANAGE_MESSAGES: 1 << 11,
  MANAGE_CHANNELS: 1 << 12,
  MANAGE_SERVER: 1 << 13,
}

let x = {
  ADMINISTRATOR: 1 << 0,
  MANAGE_SERVER: 1 << 1,
  MANAGE_CHANNELS: 1 << 2,
  MANAGE_MESSAGES: 1 << 3,
  MANAGE_ROLES: 1 << 4,
  KICK_MEMBERS: 1 << 5,
  BAN_MEMBERS: 1 << 6,
  MANAGE_NICKNAMES: 1 << 7,
  VIEW_AUDIT_LOG: 1 << 8,

  CREATE_MESSAGE: 1 << 9,
  EMBED_LINKS: 1 << 10,
  READ_MESSAGE_HISTORY: 1 << 11,  
  ADD_REACTIONS: 1 << 12,
  ATTACH_FILES: 1 << 13,
  MASS_MENTIONS: 1 << 14,

  VIEW_CHANNELS: 1 << 15,
  CREATE_INVITE: 1 << 16,
  CHANGE_NICKNAME: 1 << 17,
}